version: "3.8"
services:
  master:
    image: shac/seaweedfs
    deploy:
      mode: global
    environment:
      - MAX_VOLUME_SIZE=128
      - REPLICATION=002
    volumes:
      - ${SEAWEEDFS_DIR}/master:/data/snapshot
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
  volume:
    image: shac/seaweedfs
    deploy:
      mode: global
    environment:
      - MAX_VOLUMES=4
    volumes:
      - ${SEAWEEDFS_DIR}/volumes:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ui/index.html"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
  filer:
    image: shac/seaweedfs
    deploy:
      mode: global
    volumes:
      - ${SEAWEEDFS_DIR}/filer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s