version: "3.8"
services:
  master:
    image: shac/seaweedfs
    deploy:
      mode: global
    environment:
      - NODE="{{.Node.Hostname}}"
      - MAX_VOLUME_SIZE=128
      - REPLICATION=002
    volumes:
      - ${SEAWEEDFS_DIR}/master:/data/snapshot
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default: 
        aliases:
          - "{{.Service.Name}}.{{.Node.Hostname}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
  volume:
    image: shac/seaweedfs
    deploy:
      mode: global
    environment:
      - NODE="{{.Node.Hostname}}"
      - MAX_VOLUMES=4
    volumes:
      - ${SEAWEEDFS_DIR}/volumes:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - "{{.Service.Name}}.{{.Node.Hostname}}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ui/index.html"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
  filer:
    image: shac/seaweedfs
    deploy:
      mode: global
    environment:
      - NODE="{{.Node.Hostname}}"
    volumes:
      - ${SEAWEEDFS_DIR}/filer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default: 
        aliases:
          - "{{.Service.Name}}.{{.Node.Hostname}}"
    configs:
      - source: filer_toml
        target: /etc/seaweedfs/filer.toml
        mode: 0755
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
  etcd:
    image: appcelerator/etcd:latest
    volumes:
      - ${SEAWEEDFS_DIR}/etcd:/data
    networks:
      default: 
        aliases:
          - "{{.Service.Name}}.{{.Node.Hostname}}"
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 1
    deploy:
      mode: global
networks:
  default:
    driver: overlay
    attachable: true
configs:
  filer_toml:
    file: ./filer.toml