version: "3.8"
services:
  master:
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    image: shac/seaweedfs:latest
    deploy:
      replicas: 3
      endpoint_mode: vip
      placement:
        constraints:
          - "node.role==manager"
    environment:
      - MAX_VOLUME_SIZE=128
      - REPLICATION=002
      - NAME=/{{.Service.Name}}.{{.Task.Slot}}
    volumes:
      - ${SEAWEEDFS_DIR}/weed:/usr/bin/weed
      - ${SEAWEEDFS_DIR}/master:/data/snapshot
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
      timeout: 1s
      retries: 30
  volume:
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    image: shac/seaweedfs:latest
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==manager"
    environment:
      - MAX_VOLUMES=4
      - NAME=/{{.Service.Name}}.{{.Task.Slot}}
    volumes:
      - ${SEAWEEDFS_DIR}/weed:/usr/bin/weed
      - ${SEAWEEDFS_DIR}/volumes:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ui/index.html"]
      interval: 1s
      timeout: 1s
      retries: 30
  filer:
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    image: shac/seaweedfs:latest
    deploy:
      mode: global
    environment:
      - NAME=/{{.Service.Name}}.{{.Task.Slot}}
    configs:
      - source: filer_toml
        target: /etc/seaweedfs/filer.toml
        mode: 0755
    volumes:
      - ${SEAWEEDFS_DIR}/weed:/usr/bin/weed
      - ${SEAWEEDFS_DIR}/filer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1s
      timeout: 1s
      retries: 30
networks:
  default:
    driver: overlay
    attachable: true
configs:
  filer_toml:
    file: ../build/seaweedfs/leveldb2.toml